root = "."
tmp_dir = "tmp"

[build]
cmd = "go tool templ generate && tailwindcss -i web/static/css/input.css -o web/static/css/styles.css --minify && go build -o ./tmp/main ./cmd/server"
bin = "./tmp/main"
delay = 200
include_ext = ["go", "templ", "css", "js", "json"]
exclude_dir = ["tmp", ".git"]
exclude_regex = ["_templ.go$", "styles.css$"]
stop_on_error = true

[misc]
clean_on_exit = true
