version: "2"

run:
  timeout: 5m

linters:
  default: standard
  enable:
    - misspell
    - revive

  settings:
    errcheck:
      exclude-functions:
        - fmt.Fprint
        - fmt.Fprintln
        - fmt.Fprintf
        - (io.Writer).Write

formatters:
  enable:
    - gofmt
    - goimports
